lista_preguntas = [
    {"pregunta":"¿A quién le dicen 'Alfajor'?", "respuesta_1":"Jorgito","respuesta_2":"Manolito","respuesta_3":"Luisito","respuesta_4": "Fernandito", "respuesta_correcta":1},
    {"pregunta": "¿Qué hace una abeja en el gimnasio?", "respuesta_1": "Zumba", "respuesta_2": "Tango", "respuesta_3": "Malambo","respuesta_4": "Salsa", "respuesta_correcta": 1},
    {"pregunta": "¿Qué dijo la lista en Python cuando se sintió vacía?", "respuesta_1": "Popeame", "respuesta_2": "Cleaneame", "respuesta_3": "Discarteame","respuesta_4": "Appendeame", "respuesta_correcta": 4},
    {"pregunta": "¿Quién es conocido como el 'Padre de la Patria' en Argentina?", "respuesta_1": "Juan Manuel de Rosas", "respuesta_2": "José de San Martín", "respuesta_3": "Manuel Belgrano","respuesta_4": "Rawson", "respuesta_correcta": 2},
    {"pregunta": "¿Qué planeta va después de Marte?", "respuesta_1": "Vierne", "respuesta_2": "Lune", "respuesta_3": "Jueve","respuesta_4": "Miercole", "respuesta_correcta": 4},
    {"pregunta": "¿Qué le dice una uva verde a una morada?", "respuesta_1": "Superá", "respuesta_2": "Manejá", "respuesta_3": "Respirá","respuesta_4": "Aprobá", "respuesta_correcta": 3},
    {"pregunta": "¿Quién compuso la canción 'Gracias a la Vida'?", "respuesta_1": "Mercedes Sosa", "respuesta_2": "Charly García", "respuesta_3": "Violeta Parra","respuesta_4": "Rawson", "respuesta_correcta": 3},
    {"pregunta": "¿En qué año fue elegido presidente Néstor Kirchner?", "respuesta_1": "2000", "respuesta_2": "2003", "respuesta_3": "2007","respuesta_4": "Rawson", "respuesta_correcta": 2},
    {"pregunta": "¿En qué provincia se encuentra la ciudad de Ushuaia?", "respuesta_1": "Santa Cruz", "respuesta_2": "Chubut", "respuesta_3": "Tierra del Fuego","respuesta_4": "Rawson", "respuesta_correcta": 3},
    {"pregunta": "¿Qué moneda se utiliza en Argentina?", "respuesta_1": "Dólar", "respuesta_2": "Peso", "respuesta_3": "Real","respuesta_4": "Rawson", "respuesta_correcta": 2},
    {"pregunta": "¿Qué famoso cantante argentino popularizó el tango?", "respuesta_1": "Astor Piazzolla", "respuesta_2": "Carlos Gardel", "respuesta_3": "Sandro","respuesta_4": "Rawson", "respuesta_correcta": 2},
    {"pregunta": "¿Cuál es la danza tradicional de Argentina?", "respuesta_1": "Salsa", "respuesta_2": "Cumbia", "respuesta_3": "Tango","respuesta_4": "Rawson", "respuesta_correcta": 3},
    {"pregunta": "¿Cuál es el nombre del famoso glaciar en la Patagonia?", "respuesta_1": "Perito Moreno", "respuesta_2": "Martial", "respuesta_3": "Upsala","respuesta_4": "Rawson", "respuesta_correcta": 1},
    {"pregunta": "¿Quién es el autor de 'Martín Fierro'?", "respuesta_1": "Jorge Luis Borges", "respuesta_2": "José Hernández", "respuesta_3": "Julio Cortázar","respuesta_4": "Rawson", "respuesta_correcta": 2},
    {"pregunta": "¿Cuál es la montaña más alta de América del Sur?", "respuesta_1": "Cerro Bonete", "respuesta_2": "Monte Pissis", "respuesta_3": "Aconcagua","respuesta_4": "Rawson", "respuesta_correcta": 3},
    {"pregunta": "¿Tú y yo qué somos?", "respuesta_1": "Verbos", "respuesta_2": "Pronombres", "respuesta_3": "Sustantivos","respuesta_4": "Adjetivos", "respuesta_correcta": 2},
    {"pregunta": "¿Cuál es el nombre del teatro más famoso de Buenos Aires?", "respuesta_1": "Teatro Colón", "respuesta_2": "Teatro Gran Rex", "respuesta_3": "Teatro Nacional","respuesta_4": "Rawson", "respuesta_correcta": 1},
    {"pregunta": "¿Qué hace un programador Python cuando le rompen el corazón?", "respuesta_1": "Else", "respuesta_2": "While", "respuesta_3": "Pass","respuesta_4": "Input", "respuesta_correcta": 3},
    {"pregunta": "¿Qué prócer argentino creó la bandera?", "respuesta_1": "Domingo Sarmiento", "respuesta_2": "José de San Martín", "respuesta_3": "Manuel Belgrano","respuesta_4": "Rawson", "respuesta_correcta": 3},
    {"pregunta": "¿Por qué un boomerang sería un buen programador?", "respuesta_1": "Sabe usar el if", "respuesta_2": "Sabe usar del", "respuesta_3": "Sabe usar def","respuesta_4": "Sabe usar return", "respuesta_correcta": 4},
    {"pregunta": "¿Cuál es el superhéroe de los perros?", "respuesta_1": "El pítbull", "respuesta_2": "El dóberman", "respuesta_3": "El caniche","respuesta_4": "El dogo", "respuesta_correcta": 2},
    {"pregunta": "¿Cuál es el nombre del equipo de fútbol conocido como 'La Academia'?", "respuesta_1": "Boca Juniors", "respuesta_2": "Racing Club", "respuesta_3": "River Plate","respuesta_4": "Rawson", "respuesta_correcta": 2},
    {"pregunta": "¿En qué provincia se encuentra la ciudad de Mendoza?", "respuesta_1": "Santa Fe", "respuesta_2": "San Juan", "respuesta_3": "Mendoza","respuesta_4": "Rawson", "respuesta_correcta": 3},
    {"pregunta": "¿Cuál es el ave nacional de Argentina?", "respuesta_1": "Cóndor", "respuesta_2": "Ñandú", "respuesta_3": "Hornero","respuesta_4": "Rawson", "respuesta_correcta": 3},
    {"pregunta": "¿Qué escritora argentina ganó el Premio Cervantes en 2018?", "respuesta_1": "Silvina Ocampo", "respuesta_2": "María Elena Walsh", "respuesta_3": "María Teresa Andruetto","respuesta_4": "Rawson", "respuesta_correcta": 3},
    {"pregunta": "¿Qué le dijo el índice al elemento?", "respuesta_1": "Te cuidé", "respuesta_2": "Te encontré", "respuesta_3": "Te esperé","respuesta_4": "Te maté", "respuesta_correcta": 2}
]
